-- MySQL Script generated by MySQL Workbench
-- 11/22/14 00:07:16
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamification
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gamification` DEFAULT CHARACTER SET utf8 ;
USE `gamification` ;

-- -----------------------------------------------------
-- Table `gamification`.`achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`achievements` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL COMMENT 'суть достижения',
  `type` VARCHAR(1) NOT NULL COMMENT 'тип достижения: p-положительное, n-негативное, m-(middle) нейтральное',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'название категории бейджев \"учеба\", \"спорт\", \"досуг\"',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`universities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`universities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL COMMENT 'Название университета',
  `address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL COMMENT 'город в котором нахдится университет',
  `rating` INT(11) NOT NULL COMMENT 'рейтинг',
  `username` VARCHAR(100) NOT NULL COMMENT 'логин админа университета',
  `password` VARCHAR(100) NOT NULL COMMENT 'пароль админа университета',
  `description` VARCHAR(300) NULL DEFAULT NULL COMMENT 'описание вуза',
  `photo` VARCHAR(30) NULL DEFAULT NULL COMMENT 'фото вуза',
  `site` VARCHAR(45) NULL DEFAULT NULL COMMENT 'сайт вуза',
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`disciplines` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название предмета',
  `university_id` INT(11) NOT NULL COMMENT 'в каком вузе преподается эта дисциплина',
  `photo` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `discipline_id_idx` (`university_id` ASC),
  CONSTRAINT `university_id`
    FOREIGN KEY (`university_id`)
    REFERENCES `gamification`.`universities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`badges` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL COMMENT 'описание',
  `image` VARCHAR(30) NOT NULL COMMENT 'изображение бейджа',
  `category_id` INT(11) NOT NULL COMMENT 'к какой категории относится бейдж',
  `value` FLOAT NULL DEFAULT NULL COMMENT 'сколько баллов приносит',
  `discipline_id` INT(11) NULL DEFAULT NULL COMMENT 'к какой дисциплине добавляются баллы',
  PRIMARY KEY (`id`),
  INDEX `discipline_id_idx` (`discipline_id` ASC),
  INDEX `category_id_idx` (`category_id` ASC),
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `gamification`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discipline_id4`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `gamification`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`departments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `university_id` INT(11) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `university_id_idx` (`university_id` ASC),
  CONSTRAINT `university_id3`
    FOREIGN KEY (`university_id`)
    REFERENCES `gamification`.`universities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Название группы',
  `faculty` VARCHAR(45) NOT NULL COMMENT 'факультет',
  `department_id` INT(11) NOT NULL COMMENT 'кафедра',
  `rating` INT(11) NOT NULL COMMENT 'рейтинг',
  PRIMARY KEY (`id`),
  INDEX `department_id_idx` (`department_id` ASC),
  CONSTRAINT `department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `gamification`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`students` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL COMMENT 'группа в которой учится студент',
  `name` VARCHAR(60) NOT NULL COMMENT 'имя студента',
  `surname` VARCHAR(60) NOT NULL COMMENT 'фамилия студента',
  `username` VARCHAR(100) NOT NULL COMMENT 'логин',
  `password` VARCHAR(100) NOT NULL COMMENT 'пароль',
  `rating` INT(11) NOT NULL COMMENT 'рейтинг',
  `photo` VARCHAR(30) NOT NULL COMMENT 'аватарка студента',
  `status` VARCHAR(45) NOT NULL COMMENT 'завние(статус) студента \"студент\", \"бакалавр\", \"магистр\"',
  `year` INT(11) NOT NULL COMMENT '(год обучения в вузе) (academic) year',
  `leader` TINYINT(1) NOT NULL COMMENT 'староста',
  PRIMARY KEY (`id`),
  INDEX `group_id_idx` (`group_id` ASC),
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `gamification`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`teachers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL COMMENT 'Имя преподавателя',
  `surname` VARCHAR(60) NOT NULL COMMENT 'Фамилия преподавателя',
  `academic_rank` VARCHAR(100) NOT NULL COMMENT 'Ученое звание(ученая степень)',
  `university_id` INT(11) NOT NULL COMMENT 'в каком вузе преподает ',
  `username` VARCHAR(100) NOT NULL COMMENT 'логин',
  `password` VARCHAR(100) NOT NULL COMMENT 'пароль',
  `photo` VARCHAR(30) NOT NULL COMMENT 'аватарка преподавателя',
  PRIMARY KEY (`id`),
  INDEX `university_id_idx` (`university_id` ASC),
  CONSTRAINT `teacher_id`
    FOREIGN KEY (`university_id`)
    REFERENCES `gamification`.`universities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(300) NOT NULL COMMENT 'содержание комментария',
  `time` DATETIME NOT NULL COMMENT 'время отправления комментария',
  `checked` TINYINT(1) NOT NULL COMMENT 'проверен коммент или нет',
  `from_student_id` INT(11) NULL DEFAULT NULL COMMENT 'комент написан студентом',
  `from_teacher_id` INT(11) NULL DEFAULT NULL COMMENT 'комент написан преподавателем',
  PRIMARY KEY (`id`),
  INDEX `student_id_idx` (`from_student_id` ASC),
  INDEX `teacher_id_idx` (`from_teacher_id` ASC),
  CONSTRAINT `from_student_id`
    FOREIGN KEY (`from_student_id`)
    REFERENCES `gamification`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `from_teacher_id`
    FOREIGN KEY (`from_teacher_id`)
    REFERENCES `gamification`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`comment_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`comment_discipline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment_id` INT(11) NOT NULL,
  `discipline_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_id_idx` (`comment_id` ASC),
  INDEX `discipline_id_idx` (`discipline_id` ASC),
  CONSTRAINT `comment_id2`
    FOREIGN KEY (`comment_id`)
    REFERENCES `gamification`.`comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discipline_id5`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `gamification`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`comment_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`comment_student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment_id` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_id_idx` (`comment_id` ASC),
  INDEX `student_id_idx` (`student_id` ASC),
  CONSTRAINT `comment_id`
    FOREIGN KEY (`comment_id`)
    REFERENCES `gamification`.`comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_id4`
    FOREIGN KEY (`student_id`)
    REFERENCES `gamification`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`comment_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`comment_teacher` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment_id` INT(11) NOT NULL,
  `teacher_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_id_idx` (`comment_id` ASC),
  INDEX `teacher_id_idx` (`teacher_id` ASC),
  CONSTRAINT `comment_id3`
    FOREIGN KEY (`comment_id`)
    REFERENCES `gamification`.`comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teacher_id2`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `gamification`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`discipline_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`discipline_student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `discipline_id` INT(11) NOT NULL,
  `student_d` INT(11) NOT NULL,
  `rating` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `discipline_id_idx` (`discipline_id` ASC),
  INDEX `student_d_idx` (`student_d` ASC),
  CONSTRAINT `discipline_id6`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `gamification`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_id5`
    FOREIGN KEY (`student_d`)
    REFERENCES `gamification`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`group_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`group_discipline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL COMMENT 'у какой группы',
  `discipline_id` INT(11) NOT NULL COMMENT 'какой предмет',
  PRIMARY KEY (`id`),
  INDEX `group_id_idx` (`group_id` ASC),
  INDEX `discipline_id_idx` (`discipline_id` ASC),
  CONSTRAINT `discipline_id3`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `gamification`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `group_id2`
    FOREIGN KEY (`group_id`)
    REFERENCES `gamification`.`groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`practices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`practices` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `discipline_id` INT(11) NOT NULL COMMENT 'По какому предмету лабораторная',
  `number` INT(11) NOT NULL COMMENT 'Номер лабораторной',
  `theme` VARCHAR(100) NOT NULL COMMENT 'Тема лабораторной',
  `knowledge` VARCHAR(200) NOT NULL COMMENT 'Какие навыки приобретет студент выполнив лабу',
  `term` DATE NULL DEFAULT NULL COMMENT 'крайний срок сдачи лабораторной ',
  PRIMARY KEY (`id`),
  INDEX `discipline_id_idx` (`discipline_id` ASC),
  CONSTRAINT `discipline_id`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `gamification`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`student_achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`student_achievement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL COMMENT 'у какого студента',
  `achievement_id` INT(11) NOT NULL COMMENT 'какое достижение',
  PRIMARY KEY (`id`),
  INDEX `student_id_idx` (`student_id` ASC),
  INDEX `achievement_id_idx` (`achievement_id` ASC),
  CONSTRAINT `achievement_id`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `gamification`.`achievements` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_id3`
    FOREIGN KEY (`student_id`)
    REFERENCES `gamification`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`student_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`student_badge` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'какому студенту вручен бейдж',
  `student_id` INT(11) NOT NULL COMMENT 'кому вручен бейдж',
  `badge_id` INT(11) NOT NULL COMMENT 'какой бейдж',
  `date` DATE NOT NULL COMMENT 'дата вручения',
  PRIMARY KEY (`id`),
  INDEX `student_id_idx` (`student_id` ASC),
  INDEX `badge_id_idx` (`badge_id` ASC),
  CONSTRAINT `badge_id`
    FOREIGN KEY (`badge_id`)
    REFERENCES `gamification`.`badges` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_id2`
    FOREIGN KEY (`student_id`)
    REFERENCES `gamification`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`student_practice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`student_practice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL COMMENT 'кто выполнил лабораторную',
  `practice_id` INT(11) NOT NULL COMMENT 'какую лабораторную выполнил',
  `mark` FLOAT NOT NULL COMMENT 'оценка',
  `date` DATE NOT NULL COMMENT 'дата сдачи лабораторной',
  `attend` TINYINT(1) NOT NULL COMMENT 'присутствие студента на паре 1-был 0-энка',
  PRIMARY KEY (`id`),
  INDEX `student_id_idx` (`student_id` ASC),
  INDEX `practice_id_idx` (`practice_id` ASC),
  CONSTRAINT `practice_id`
    FOREIGN KEY (`practice_id`)
    REFERENCES `gamification`.`practices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `gamification`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamification`.`teacher_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gamification`.`teacher_discipline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `teacher_id` INT(11) NOT NULL COMMENT 'кто преподает',
  `discipline_id` INT(11) NOT NULL COMMENT 'что преподает',
  PRIMARY KEY (`id`),
  INDEX `teacher_id_idx` (`teacher_id` ASC),
  INDEX `discipline_id_idx` (`discipline_id` ASC),
  CONSTRAINT `discipline_id2`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `gamification`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teacher_id3`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `gamification`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
